// components/services/BIBLE_BOOKS.js

export const BIBLE_BOOKS = [
  { value: 'GEN', label: 'Genèse' },
  { value: 'EXO', label: 'Exode' },
  { value: 'LEV', label: 'Lévitique' },
  { value: 'NUM', label: 'Nombres' },
  { value: 'DEU', label: 'Deutéronome' },
  { value: 'JOS', label: 'Josué' },
  { value: 'JDG', label: 'Juges' },
  { value: 'RUT', label: 'Ruth' },
  { value: '1SA', label: '1 Samuel' },
  { value: '2SA', label: '2 Samuel' },
  { value: '1KI', label: '1 Rois' },
  { value: '2KI', label: '2 Rois' },
  { value: '1CH', label: '1 Chroniques' },
  { value: '2CH', label: '2 Chroniques' },
  { value: 'EZR', label: 'Esdras' },
  { value: 'NEH', label: 'Néhémie' },
  { value: 'EST', label: 'Esther' },
  { value: 'JOB', label: 'Job' },
  { value: 'PSA', label: 'Psaumes' },
  { value: 'PRO', label: 'Proverbes' },
  { value: 'ECC', label: 'Ecclésiaste' },
  { value: 'SNG', label: 'Cantique des cantiques' },
  { value: 'ISA', label: 'Esaïe' },
  { value: 'JER', label: 'Jérémie' },
  { value: 'LAM', label: 'Lamentations' },
  { value: 'EZK', label: 'Ezéchiel' },
  { value: 'DAN', label: 'Daniel' },
  { value: 'HOS', label: 'Osée' },
  { value: 'JOL', label: 'Joël' },
  { value: 'AMO', label: 'Amos' },
  { value: 'OBA', label: 'Abdias' },
  { value: 'JON', label: 'Jonas' },
  { value: 'MIC', label: 'Michée' },
  { value: 'NAM', label: 'Nahum' },
  { value: 'HAB', label: 'Habaquq' },
  { value: 'ZEP', label: 'Sophonie' },
  { value: 'HAG', label: 'Aggée' },
  { value: 'ZEC', label: 'Zacharie' },
  { value: 'MAL', label: 'Malachie' },
  { value: 'MAT', label: 'Matthieu' },
  { value: 'MRK', label: 'Marc' },
  { value: 'LUK', label: 'Luc' },
  { value: 'JHN', label: 'Jean' },
  { value: 'ACT', label: 'Actes' },
  { value: 'ROM', label: 'Romains' },
  { value: '1CO', label: '1 Corinthiens' },
  { value: '2CO', label: '2 Corinthiens' },
  { value: 'GAL', label: 'Galates' },
  { value: 'EPH', label: 'Ephésiens' },
  { value: 'PHP', label: 'Philippiens' },
  { value: 'COL', label: 'Colossiens' },
  { value: '1TH', label: '1 Thessaloniciens' },
  { value: '2TH', label: '2 Thessaloniciens' },
  { value: '1TI', label: '1 Timothée' },
  { value: '2TI', label: '2 Timothée' },
  { value: 'TIT', label: 'Tite' },
  { value: 'PHM', label: 'Philémon' },
  { value: 'HEB', label: 'Hébreux' },
  { value: 'JAS', label: 'Jacques' },
  { value: '1PE', label: '1 Pierre' },
  { value: '2PE', label: '2 Pierre' },
  { value: '1JN', label: '1 Jean' },
  { value: '2JN', label: '2 Jean' },
  { value: '3JN', label: '3 Jean' },
  { value: 'JUD', label: 'Jude' },
  { value: 'REV', label: 'Apocalypse' }
];